- haxe/ui/toolkit/controls/popups/Popup.hx
Fixes a null object reference when trying to drag popups without a title bar. Also makes it possible to enable dragging from outside the title bar by setting the dragAnywhere config property to true.
> Dragging of popups outside title bar.

- haxe/ui/toolkit/controls/popups/Popup.hx
- haxe/ui/toolkit/core/PopupManager.hx
- haxe/ui/toolkit/core/Root.hx
To close #93.
You can control how a popup can be dismissed by setting the "dismiss" config property to one or more of the followin flags defined in the Dismiss class:
ESCAPE - Press escape.
ANYKEY - Press any key.
CLICK_OUTSIDE - Click outside the popup (on the modal overlay).
CLICK_INSIDE - Click on the popup.
CLICK - Click anywhere.
If more than one modal popup is visible at the same time, all actions except CLICK_INSIDE will try to close the most recently created.
The callback function will be called with PopupButton.CANCEL as argument.
> Dismissing modal popups

- haxe/ui/toolkit/controls/Button.hx
- haxe/ui/toolkit/controls/Image.hx
If you specify *just* the width or height of an image the other will now automatically scale, while maintaining image ratio.
Specifying both will stretch the image to that size.
Specifying neither will use the image's original dimensions.
I've removed the `stretch` property as it no longer makes sense.
Resolves #143, but not completely compat with older code. If we wanted to maintain backward compatibility we could reintroduce `stretch` as an ignored, but present property (as they'd presumably be including both a `width` and `height` alongside `stretch` anyway. And functionality would be matched when that is the case).
> Aspect-correct Image scaling

- haxe/ui/toolkit/controls/Image.hx
Also fixes cases where scaling gif and svg images down to 0 width or
height and then enlarging again would break scaling (as ratio would get
stuck at 0)
> code tidy for aspect-correct image scaling

- haxe/ui/toolkit/controls/Image.hx
Images currently pixelate when enlarged and "sparkle" when shrunk, so I've enabled filtering. This seems a better sensible default, and shouldn't add any additional performance overhead.
(Note that they'll still sparkle when shrunk below 50% size, cos there's no mipmaps)
> added: image smoothing to Image controls

- haxe/ui/toolkit/containers/ScrollView.hx
When you did a quick scroll on mobile and then tapped on a control, the first tap was always ignored, the scrollbars remained onscreen, even when autohide was enabled.
> fixed: the first tap after an inertial scroll was ignored and autoHideScrolls was not working

- haxe/ui/toolkit/controls/Button.hx
Text objects can sometimes be taller than their DisplayObjects when they're multiline/wordWrap, due the TextField sizing before the correct styling has been assigned, and Buttons then locking the Text height before the TextField is recalculated with the correct height. This can
lead to extra vertical space below button labels. autoSize should always be left on to correct for this.
(Note also the modified code is for width constraint, but autoSize only affects height when TextFields have wordWrap)
> fixed: Buttons with multiline labels did not always vertically align correctly

- xsd/layout-1.0.0.xsd
Using the XSD enables auto-completion and basic validation in XSD aware editors. 
XSD validation is set to **lax** for unknown elements/attributes to avoid that the editors raise errors for new elements/attributes.
The XSD should be made availabe for download at http://haxeui.org/xsd/layout-1.0.0.xsd
Example Usage:
<vbox
xmlns="http://haxeui.org/layout/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://haxeui.org/layout/1.0.0 http://haxeui.org/xsd/layout-1.0.0.xsd"
>
</vbox>
>  	added XSD for HaxeUI XML definition files

- haxe/ui/toolkit/text/TextDisplay.hx
Textfields aren't clickable so the label click event on Checkboxes wasn't firing. (I'm guessing it did at some point in time, but it's borked now :/) I've made all Text report mouse events for now.
I could have used the `interactive` property, but that would have made the text editable, too.
Checkboxes without clickable labels are very sad, and especially awkward on mobile :(
> fixed: Checkbox labels weren't clickable

- haxe/ui/toolkit/controls/CheckBox.hx
Because checkboxes deserve multiline and wrapLines love too.
This is designed to be used with autoSize=false, and a set width.
I haven't fully tested this in all layout scenarios, buut I think it should be good.
> added: wrapLines property to checkboxes

- haxe/ui/toolkit/console/HaxeUIConsoleFunctions.hx
- haxe/ui/toolkit/containers/ListView.hx
- haxe/ui/toolkit/containers/SpriteContainer.hx
- haxe/ui/toolkit/core/xml/DataProcessor.hx
- haxe/ui/toolkit/core/xml/UIProcessor.hx
- haxe/ui/toolkit/util/Types.hx
Instead of such an obscure exception
$nargs
Called from Type::createInstance line 102
Called from haxe.ui.toolkit.core.xml.UIProcessor::createComponent line 57
Called from haxe.ui.toolkit.core.xml.UIProcessor::process line 51
Called from haxe.ui.toolkit.core.Toolkit::processXmlNode line 187
a meaning full exception will be thrown:
Cannot find class with name [haxe.ui.toolkit.containers.Absolute]
Called from haxe.ui.toolkit.util.Types::resolveClass line 12
Called from haxe.ui.toolkit.core.xml.UIProcessor::createComponent line 57
Called from haxe.ui.toolkit.core.xml.UIProcessor::process line 51
Called from haxe.ui.toolkit.core.Toolkit::processXmlNode line 187
This is especially important when troubleshooting DCE issues as reported in #283
> Better error reporting when class is not found

- haxe/ui/toolkit/controls/Image.hx
Instead of this obscure error message:
Invalid field access : get_width
Called from haxe.ui.toolkit.controls.Image::updateContent line 330
Called from haxe.ui.toolkit.controls.Image::initialize line 59
Called from haxe.ui.toolkit.core.DisplayObject::_onAddedToStage line 84
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
This will be thrown now:
Image [themes/shared/arrow_up.png] not found!
Called from haxe.ui.toolkit.controls.Image::loadBitmap line 243
Called from haxe.ui.toolkit.controls.Image::set_resource line 163
Called from haxe.ui.toolkit.controls.Button::set_icon line 150
Called from haxe.ui.toolkit.controls.Button::applyStyle line 667
Called from haxe.ui.toolkit.core.StyleableDisplayObject::refreshStyle line 323
Called from …
> Throw meaningful exception when image resource was not found

- haxe/ui/toolkit/controls/Button.hx
Once a non-selectable button had been marked as selected and then non-selected, it retained its _down state, causing it respond to mouseover+down events, even though it was non-selectable.
In the case of mobile devices this made non-selectable buttons respond to taps, once they had been toggled once, even when non-selectable.
> fixed: toggling selected on a Button could put it in a weird state (particularly on mobile)

- haxe/ui/toolkit/core/xml/UIProcessor.hx
For example: onDoubleClick would look for event "doubleclick", not "doubleClick", so was non-functional :(
> fixed: only fully lowercase events worked in xml

- haxe/ui/toolkit/core/Component.hx
scriptlets can now use `this` to access the component that executed them
(useful for writing onEvent handlers in xml)
> Added scriptlet this support

- haxe/ui/toolkit/containers/ScrollView.hx
- haxe/ui/toolkit/controls/HScroll.hx
- haxe/ui/toolkit/controls/VScroll.hx
- haxe/ui/toolkit/core/DisplayObject.hx
- haxe/ui/toolkit/events/UIEvent.hx
HScrolls, VScrolls and ScrollViews now emit `scrollStart` and `scrollStop` events when a scroll begins and finally ends (so `scrollStop` fires when the mouse/finger/device is released).
Useful for if you need the ui to perform snapping or adjustments after a user has halted interaction.
For conformity HScrolls and VScrolls now emit `scroll` events as well as `change` events, as they are adjusted.
> added: scrollStart and scrollStop events

- haxe/ui/toolkit/style/StyleParser.hx
Using a style selector like `".stylea, .styleb"` and then adding a second style affecting just `stylea` would also affect `styleb` as they were linked to the same instance
> fixed: runtime comma-separated styles were linked

- haxe/ui/toolkit/controls/CheckBox.hx
Adding the Click listener to the checkbox and not the label component (the same way it is done for the optionbox). This solves #316
> make checkbox label clickable

- haxe/ui/toolkit/core/Component.hx
Hi.
You can't assign the disabled property twice because a listener is lost in the next time. 
Here a simple example:
```
Toolkit.openFullscreen(function(root:Root) {
var button = new Button();
button.width = 100;
button.height = 50;
button.text = "Click Me";
button.addEventListener(UIEvent.CLICK, function(e:UIEvent){
trace("Click 1");
});
button.addEventListener(UIEvent.CLICK, function(e:UIEvent){
trace("Click 2");
});
button.disabled = true;
button.disabled = true;   //The problem
button.disabled = false;
root.addChild(button);
});
```
I have implemented a simple check if disabled == value to avoid unnecesary work.
Kind Regards.
> The Disabled property doesn't work properly if it was assigned twice.

- haxe/ui/toolkit/controls/CheckBox.hx
Seems #292 was overwritten by 3f5a332a939015249720bfb5ddd142be8b69a6df.
As mouse interaction with TextDisplays is a slight cause of problems I've used a clickable eventTarget over the whole checkbox and label instead, similiar to scrollviews.
Checkboxes very much need this on mobile.
> Fixed: checkbox labels not clickable

- haxe/ui/toolkit/containers/ScrollView.hx
The "SCROLL_STOP" event should dispatch when the inertia is finished.
For example, you have a list of thumbnails and you want to load the thumbnails in screen when the SCROLL_STOP is dispatched.
> Fix scroll stop event

- haxe/ui/toolkit/core/DisplayObject.hx
...by adding parent sprite positions of root.
Please see #221.
I've only tested with a ListSelector. I don't know if it has any consequence on other widgets.
> fix #221 stageX and stageY correct computations
